export const companies = [
    {
        id: 1,
        lastName: 'K.',
        dataName: 'Anadolia',
        surname: "Lorem ipsum dolor",
        email: 'abc@xyz.com',
        district: "Istanbul/Tuzla",
        age: 35,
        company: 'frimex',
        companyName: 'frimex',
    },
    {
        id: 2,
        lastName: 'A.',
        dataName: 'Anadolia',
        surname: "Lorem ipsum dolor",
        email: 'abc@xyz.com',
        district: "Istanbul/Tuzla",
        age: 42,
        company: 'frimex',
        companyName: 'frimex',
    },
    {
        id: 3,
        lastName: 'S.',
        dataName: 'Demo',
        surname: "Lorem ipsum dolor",
        email: 'abc@xyz.com',
        district: "Istanbul/Tuzla",
        age: 45,
        company: 'frimex',
        companyName: 'frimex',
    },
    {
        id: 4,
        lastName: 'Q.',
        dataName: 'GCode',
        surname: "Lorem ipsum dolor",
        email: 'abc@xyz.com',
        district: "Istanbul/Tuzla",
        age: 16,
        company: 'frimex',
        companyName: 'frimex',
    },
    {
        id: 5,
        lastName: 'C.',
        dataName: 'Green',
        surname: "Lorem ipsum dolor",
        email: 'abc@xyz.com',
        district: "Istanbul/Tuzla",
        age: null,
        company: 'frimex',
        companyName: 'frimex',
    },
    {
        id: 6,
        lastName: 'X.',
        dataName: "Green",
        surname: "Lorem ipsum dolor",
        email: 'abc@xyz.com',
        district: "Istanbul/Tuzla",
        age: 150,
        company: 'frimex',
        companyName: 'frimex',
    },
    {
        id: 7,
        lastName: 'A.',
        dataName: 'Halim',
        surname: "Lorem ipsum dolor",
        email: 'abc@xyz.com',
        district: "Istanbul/Tuzla",
        age: 44,
        company: 'frimex',
        companyName: 'frimex',
    },
    {
        id: 8,
        lastName: 'P.',
        dataName: 'Helena',
        surname: "Lorem ipsum dolor",
        email: 'abc@xyz.com',
        district: "Istanbul/Tuzla",
        age: 36,
        company: 'frimex',
        companyName: 'frimex',
    },
    {
        id: 9,
        lastName: 'A.',
        dataName: 'Halim',
        surname: "Lorem ipsum dolor",
        email: 'abc@xyz.com',
        district: "Istanbul/Tuzla",
        age: 65,
        company: 'frimex',
        companyName: 'frimex',
    },
]